#!/bin/bash
set -e

printf "\n\e[0;32m🍣   Starting elm-live...\e[0m\n\n"
cmd/extra/reset | true
node_modules/.bin/elm-go src/Main.elm --open=true --start-page="index.html" --dir=docs --port=8001 --path-to-elm=node_modules/.bin/elm -- --output="docs/js-compiled/main.js"
